### PR TITLE
gh-12730: conflict keybord shortcut name always shows "Escape"

### LINKED ISSUE #12730: Conflict warning in keyboard-shortcuts page points to the wrong item
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

In `about:settings#zenCKS` (Zen's internal page for keyboard shortcuts), if the user tries to assign a keyboard shortcut that already exists for a different function, Zen displays a warning under the textbox in red:
```
Conflicts with [Group] -> [Function]
```

Currently, this warning is always <code>[Group] -> **Escape**</code> instead of whatever function the shortcut is actually assigned to.

I'm personally not sure what the `Escape` implies here, as no such shortcut exists in the page. My guess is that it's capturing the <kbd>Esc</kbd> that the user pressed in order to confirm the shortcut.

### Expected behavior

(From the recording): Warning shows `Conflicts with Workspaces -> Close All Unpinned Tabs`

### Actual behavior

Warning shows `Conflicts with Workspaces -> Escape`

### Steps to reproduce

1. Visit `about:settings#zenCKS`.
2. In a textbox, assign a duplicate shortcut (f.e. <kbd>Ctrl</kbd> <kbd>T</kbd>) and press <kbd>Esc</kbd> to confirm it.
3. The warning text will show:
   ```
   Conflicts with Window & Tab Management -> Escape
   ```

### Screenshots and videos

https://github.com/user-attachments/assets/4e575bf3-7ff4-42ca-923f-5fcc86768efc

### Version

1.19.1b

### What platform are you seeing the problem on?

Linux (Tarball)

### What component is this issue related to?

Keyboard Shortcuts

### Relevant log output if applicable

```shell
N/A
```

### PR DESCRIPTION
**Pull request by TheSilvered**
Fix a bug in the keyboard shortcuts page where when a shortcut has a conflict it always shows "Conflict with <group> -> Escape" instead of the correct name.
Resolves #12730

### CODE REVIEW

**Comment by mr-cheffy** [comment]
Could you please create an issue or find an existing issue to link this PR to?

**Review by mr-cheffy — APPROVED** [review]

File: src/browser/components/preferences/zen-settings.js [hunk 1]
```diff
@@ -1082,7 +1082,7 @@ var gZenCKSSettings = {
 
           document.l10n.setAttributes(input.nextElementSibling, "zen-key-conflict", {
             group: group ?? "",
-            shortcut: shortcut ?? "",
+            shortcut: conflictName ?? "",
```
Comment (mr-cheffy) [inline src/browser/components/preferences/zen-settings.js]: Maybe it should now be

```suggestion
            shortcut: conflictName ?? shortcut ?? "",
```

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

**Comment by Ivaon** [comment]
> Could you please create an issue or find an existing issue to link this PR to?

There's this one #12730

File: src/browser/components/preferences/zen-settings.js (hunk 1 above)
Comment (TheSilvered) [reply src/browser/components/preferences/zen-settings.js]: I don't think it makes much sense, `shortcut` is always "Escape" (see line 1050 `else if (shortcut == "Escape" && !modifiersActive)`, looking at the history the name originally was shadowed but the variable was removed when changing lint options

**Comment by TheSilvered** [comment]
> Could you please create an issue or find an existing issue to link this PR to?

I edited the description linking the issue, hopefully it works

File: src/browser/components/preferences/zen-settings.js (hunk 1 above)
Comment (mr-cheffy) [reply src/browser/components/preferences/zen-settings.js]: True, its just a bit of a safe guard in case we missed some L10n strings

**Review by mr-cheffy — APPROVED** [review]
