### PR TITLE
Glance: reduce Windows scroll lag by skipping blur and adding compositor hints

### LINKED ISSUE #10382: Scrolling lag when looking at preview (glance) of a webpage when using mouse input
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When clicking on a link within a webpage, a preview (glance) opens, this preview (glance) is often has high scrolling lag. Some site will have more lag than others, but all are significantly higher than the base page. If the page is expanded to a new tab, the lag issue goes away. This only occurs when using an external mouse and not the trackpad.

### Expected behavior

The preview (glance) window behaves with no greater lag than the base webpage

### Actual behavior

The preview (glance) window behaves with significantly greater lag than the base webpage

### Steps to reproduce

1. Open zenbrowser on a standard windows laptop/device
2. Open the Atlantic
3. Alt click on the main article
4. Scroll with an external mouse

### Screenshots and videos

**Video of me replicating the issue:**
To demonstrate lag, when the scroll bar reaches the top, I move my scroll wheel down as fast as I can. As is evident, there is a noticeable time when the scrollbar reaches the top and stays there before moving down. 

In addition, you can see that I start moving down sometimes, before it reaches the top, showing that due to the lag, it is difficult to predict the position of the scroll bar.

https://drive.google.com/file/d/1erKPTZsfYHWGkltXkk15R277muLZE-Qm/view?usp=sharing

### Version

1.15.5b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Glance

### Relevant log output if applicable

```shell

```

### PR DESCRIPTION
**Pull request by PGrayCS**
## Summary fixes #10382
This PR addresses high scroll lag in the Glance preview on Windows when using an external mouse. When the preview is expanded to a full tab, the lag disappears; the issue is isolated to the Glance overlay.

## What changed
- Windows-only: Skip `backdrop-filter: blur(...)` during Glance open/close background animations to avoid main-thread painting that degrades async scrolling (APZ) and causes wheel jank.
- Non-Windows: Keep the existing blur effect and visuals unchanged.
- Add CSS `will-change` hints to the overlay and browser containers to promote layers and smooth compositor-driven animations.

## Why this fixes the issue
Backdrop blur on Windows is expensive and can force synchronous painting during scroll, disrupting APZ paths. Removing blur for the Glance background on Windows preserves async scrolling so the preview’s scroll responsiveness matches the base page.

## Verification steps
1. Windows x64 laptop/desktop with an external mouse.
2. Open a site (e.g., The Atlantic).
3. Trigger Glance (e.g., Alt-click the main article).
4. Scroll rapidly with the mouse wheel.

Expected: Glance scroll responsiveness is similar to the base page; the brief “stuck at top” pause disappears or is greatly reduced. Expanding Glance to a new tab remains unchanged.

## Visual impact
- Windows: Background dimming uses opacity (no blur) while Glance is open; a subtle scale is preserved for depth. If stronger dimming is desired, we can tweak the opacity.
- macOS/Linux: No change.

## Files changed
- `src/zen/glance/ZenGlanceManager.mjs`
- `src/zen/glance/zen-glance.css`

## Risks and mitigations
- Visual parity on Windows: Blur is replaced with opacity dimming. If it’s too light or dark on some setups, we can adjust values or make it configurable.

## Follow-ups (optional)
- Add a pref (e.g., `zen.glance.windows.blur`) to let users opt back into blur on Windows.
- Consider GPU/driver-based gating if specific hardware still shows lag.

### CODE REVIEW

File: src/zen/glance/ZenGlanceManager.mjs [hunk 1]
```diff
@@ -318,14 +331,22 @@
             sidebarButtons.remove();
           });
       }
-      gZenUIManager.motion
-        .animate(
-          browserSidebarContainer,
-          {
+      const isWindows = AppConstants.platform === 'win';
+      const backgroundCloseAnimationProps = isWindows
```
Comment (mr-cheffy) [inline src/zen/glance/ZenGlanceManager.mjs:335]: @PGrayCS please change this to **all** OSs as this affects all of them. I'd also change the opacity to `0.8`

**Review by mr-cheffy — CHANGES_REQUESTED** [review]
Nice catch! Could you please run `npm run lint:fix` to fix the linter errors?

**Comment by mr-cheffy** [comment]
Could you also please add `15px` to `top` for `.zen-glance-sidebar-container` while we are at it?

**Comment by mr-cheffy** [comment]
@PGrayCS i've fixed these. Could you please check "allow mantainers to make changes" on the github sidebar?
