### PR TITLE
fix: Hide folder icon remove action when no icon is set, b=closes #12401, c=folders, common

### LINKED ISSUE #12401: Trash icon appears in ‘Change Icon’ menu for folders with no icon
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When creating a new folder in my space, right-clicking it and selecting Change Icon shows a trash icon even though the folder doesn’t have an icon yet. The trash icon works correctly when an icon exists, but it probably shouldn’t appear when there’s nothing to delete.

### Expected behavior

not showing the trash icon when no icon

### Actual behavior

showing the trash icon

### Steps to reproduce

having a folder with no icon > right-clicking it and selecting Change Icon 

### Screenshots and videos

here you can see the trash icon in `uni` folder that does not have an icon to delete
Image

### Version

1.18.7b (Firefox 147.0.3) (64-bit)

### What platform are you seeing the problem on?

Linux (AppImage)

### What component is this issue related to?

Tab Folders

### Relevant log output if applicable

```shell

```

### PR DESCRIPTION
**Pull request by AndreNijman**
## Summary
- hide the remove/trash action in the folder “Change Icon” picker when the folder has no custom icon
- keep the remove action available when a folder icon is already set
- add a picker option to control remove-action visibility without changing behavior for other picker call sites

## Fixed issue
- Closes #12401

### CODE REVIEW

**Comment by mr-cheffy** [comment]
I think we should also *not* hide the popup when selecting an icon, like this:


https://github.com/user-attachments/assets/1e3e29c8-21fb-4e36-a0c9-13a31629248f

**Comment by AndreNijman** [comment]
I made that change 👍, but it doesnt look as good as the video you sent as it does not have those animations.

**Comment by mr-cheffy** [comment]
https://github.com/user-attachments/assets/05ad588f-2543-4ebd-8cc2-43e70196cb2b

Looks great! But some instances of the emoji pickers close when selecting still?

File: src/zen/folders/ZenFolders.mjs [hunk 1]
```diff
@@ -903,15 +903,22 @@ class nsZenFolders extends nsZenDOMOperatedFeature {
...
         group.dispatchEvent(new CustomEvent("TabGroupUpdate", { bubbles: true }));
-      })
-      .catch((err) => {
-        console.error(err);
-      });
+      },
+    });
+
+    pickerPromise?.catch((err) => {
+      if (err?.message === "Emoji picker closed without selection") {
```
Comment (mr-cheffy) [inline src/zen/folders/ZenFolders.mjs]: No need to have this?

File: src/zen/folders/ZenFolders.mjs [hunk 2]
```diff
@@ -903,15 +903,22 @@ class nsZenFolders extends nsZenDOMOperatedFeature {
       return;
     }
 
-    gZenEmojiPicker
-      .open(group.icon, { onlySvgIcons: true })
-      .then((icon) => {
+    const pickerPromise = gZenEmojiPicker.open(group.icon, {
+      onlySvgIcons: true,
+      allowNone: Boolean(group.icon?.querySelector("svg .icon image")?.getAttribute("href")),
```
Comment (mr-cheffy) [inline src/zen/folders/ZenFolders.mjs]: Use `group.iconURL`

File: src/zen/folders/ZenFolders.mjs [hunk 3]
```diff
@@ -903,15 +903,22 @@ class nsZenFolders extends nsZenDOMOperatedFeature {
       return;
     }
 
-    gZenEmojiPicker
-      .open(group.icon, { onlySvgIcons: true })
-      .then((icon) => {
+    const pickerPromise = gZenEmojiPicker.open(group.icon, {
```
Comment (mr-cheffy) [inline src/zen/folders/ZenFolders.mjs]: No need to even store the promise at this point, you can also just remove the `catch` statement

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

**Review by mr-cheffy — APPROVED** [review]
