### PR TITLE
Fix other popover layou issues

### LINKED ISSUE #12782: macOS: Context Menu Items Cut Off at Bottom
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

The context menu is using the available space on screen, if the height of the screen is too short, then the items at the bottom can not be seen.

### Expected behavior

Show all the avaiable items when scrolling to the bottom

### Actual behavior

Items at the bottom are cut off.

### Steps to reproduce

1. Change display settings to larger text(1147x745)
2. Open Twilight/Zen
3. Open application menu by click the top right button

### Screenshots and videos

Image

### Version

1.20t (Firefox 148.0.2) (2026-03-15) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Settings

### Relevant log output if applicable

```shell
I think this is pure UI issues, I couldn't find the responsible component just yet.
```

### PR DESCRIPTION
**Pull request by bo2themax**
For popovers triggered by **History, List All Tabs, Library** and **Overflow** menu, there is still a chance that the content is cut off. (See the attachments bellow)

This pr serves as a follow-up to #12782:
- Add height constraint to more popup windows
  - `customisationui-widget-panel`: Triggered by History/List All Tabs/Library/Account/Forget/Developer button in the toolbar
  - `widget-overflow`: Overflow button in the toolbar

Following two commits can be dropped out if you feel like they're not an issue

- Hide popover arrow when panel height is maxed out
  Co-Authored-By: Claude Opus 4.6
- Update `widget-overflow` panel width the same as `appMenu-popup`

### AI Disclosure

Used Claude to generate comments and small refactors

Some comparison between Twilight and local build

[History in Overflow](https://github.com/user-attachments/assets/8e417bec-8006-43c0-9b73-ad40b4141b8a)
[History](https://github.com/user-attachments/assets/3e94b00b-1308-44c9-999a-121430b5d4ab)
[Hiding arrow based on height](https://github.com/user-attachments/assets/b240626a-6de4-4e0c-8b55-0887dc4b2212)

### CODE REVIEW

File: src/zen/common/modules/ZenUIManager.mjs [hunk 1]
```diff
@@ -338,15 +338,23 @@ window.gZenUIManager = {
...
     // conservative upper bound.
     const popoverChrome = 26;
-    panel.style.maxHeight = `${window.screen.availHeight - popoverChrome}px`;
+    const anchorHeight = panel.anchorNode?.getBoundingClientRect().height ?? 30;
+    const maxHeight = window.screen.availHeight - popoverChrome;
+    panel.style.maxHeight = `${maxHeight}px`;
+    // Maxed-out panels with arrows look ugly on smaller/normal screens,
+    // and we don't want to patch panelUI.inc.xhtml for now, so we hide them here.
+    if (panel.id === "widget-overflow" || panel.getBoundingClientRect().height >= maxHeight - anchorHeight) {
+      panel.setAttribute("hidepopovertail", "true");
```
Comment (mr-cheffy) [inline src/zen/common/modules/ZenUIManager.mjs]: Please remove this, tail doesn't actually affect height anyways

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

**Review by mr-cheffy — APPROVED** [review]

File: src/zen/common/modules/ZenUIManager.mjs (hunk 1 above)
Comment (bo2themax) [reply src/zen/common/modules/ZenUIManager.mjs]: I know it doesn't affect height, as the comment says when the height is maxed out, the arrow will be in a corner and it doesn't appear as a proper arrow anymore

**Comment by bo2themax** [comment]
@mr-cheffy Here are some examples when the `popovertail` doesn't behave ~~properly~~ nicely.

The comment above wasn't fully accurate. This happens when the popover appears on the edge of the screen, and os tries to put the arrow where the proposed position is as near as possible.

image
image
