### PR TITLE
fix: Fixed Incorrect (Reset pinned tab/Replace pinned url) Text on Essential tab context menu.

### LINKED ISSUE #12177: Incorrect Text - Resetting an Essential Tab should be called "Reset Essential Tab" instead of "Reset Pinned Tab"
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

1) Make an Essential Tab
2) Right Click on Essential Tab
3) Look at last 2 options of the Menu
4) Read the option Text

Image

### Expected behavior

Should say "Replace Essential URL with Current" and "Reset Essential Tab"

### Actual behavior

Rays "Replace Pinned URL with Current" and "Reset Pinned Tab"

### Steps to reproduce

1) Make an Essential Tab
2) Right Click on Essential Tab
3) Look at last 2 options of the Menu
4) Read the option Text

Image

### Screenshots and videos

Image

### Version

1.18.3b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

### PR DESCRIPTION
**Pull request by Retr0ville**
Added conditional labels for reset pinned tabs and replace pinned url options based on whether they are in an `$isEssential` tab context menu or not.

I've Tested and confirmed that Essential tab context menu now correctly shows "Reset Essential tab" and "Replace Essential URL with current", while Pinned tabs context menu retains existing behaviour

Fixes #12177

### CODE REVIEW

**Review by mr-cheffy — CHANGES_REQUESTED** [review]
Please just edit the text for en-US, no need to do the other languages

**Comment by Retr0ville** [comment]
> Please just edit the text for en-US, no need to do the other languages

Alright, just did that.

I'm assuming there's a crowdin workflow that handles the other translations.

File: src/zen/tabs/ZenPinnedTabManager.mjs [hunk 1]
```diff
@@ -531,8 +531,12 @@ class nsZenPinnedTabManager extends nsZenDOMOperatedFeature {
     const isVisible = contextTab.pinned && !contextTab.multiselected;
     const isEssential = contextTab.getAttribute("zen-essential");
     const zenAddEssential = document.getElementById("context_zen-add-essential");
-    document.getElementById("context_zen-reset-pinned-tab").hidden = !isVisible;
-    document.getElementById("context_zen-replace-pinned-url-with-current").hidden = !isVisible;
+    const zenResetPinnedTab = document.getElementById("context_zen-reset-pinned-tab");
+    zenResetPinnedTab.hidden = !isVisible;
+    document.l10n.setArgs(zenResetPinnedTab, { isEssential: !!isEssential });
```
Comment (mr-cheffy) [inline src/zen/tabs/ZenPinnedTabManager.mjs]: Could this be done into a for-loop maybe? To prevent writing the same thing over and over again. For `[zenResetPinnedTab, zenReplacePinnedUrl]`

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

File: src/zen/tabs/ZenPinnedTabManager.mjs (hunk 1 above)
Comment (Retr0ville) [reply src/zen/tabs/ZenPinnedTabManager.mjs]: done

**Review by mr-cheffy — APPROVED** [review]
