### PR TITLE
Fix #3887 and #3558

### LINKED ISSUE #3558: Changing mod string preferences sometimes results in missing characters
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm writing this after getting this [bug report](https://github.com/Uiniel/zen-mods/issues/1) and being able to reproduce this myself.

When changing the string preferences of a mod sometimes there are sometimes characters missing from the saved string, even though they are shown in the preferences. 

In the sidebar hover mod this bug is quite visible, it only seems to save the string when the sidebar is flickering (from changing it's width value) and typing to fast after that results in missing characters.

image
image

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

_No response_

### LINKED ISSUE #3887: Mod default preferences not displayed correctly until reopening the settings page or browser restart
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I tried this out on a new profile.

Steps to reproduce:
- Open preferences page in a tab and keep it open
- Install a mod with a default value of true for some setting (e.g. Nyan Catto Mod or Sidebar Expand on Hover)
- open the mod setting in the previously opened tab

The settings page of the mod doesn't show the correct default settings:
image
image
but in about:config the correct settings are enabled
image

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by JosueGalRe**
commit descriptions

### CODE REVIEW

File: src/browser/components/preferences/zen-settings.js [hunk 1]
```diff
@@ -439,8 +439,8 @@ var gZenMarketplaceManager = {
               }
 
               input.addEventListener(
-                'change',
-                ZenThemesCommon.throttle((event) => {
+                'keydown',
```
Comment (mr-cheffy) [inline src/browser/components/preferences/zen-settings.js]: Shoudn't we change it to `input` event?

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

File: src/browser/components/preferences/zen-settings.js (hunk 1 above)
Comment (JosueGalRe) [reply src/browser/components/preferences/zen-settings.js]: Sure

**Review by mr-cheffy — APPROVED** [review]
Looks great!
