### PR TITLE
fix: remove mozilla services from app menu

### LINKED ISSUE #10854: Mozilla services miscredited in user menu
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

After signing in with a Mozilla account, there are several Mozilla services (Monitor & Mozilla VPN) in the menu that shows up when clicking on the avatar button in the menu bar. They are described as "protection tools from Zen OSS Team", which is not the case. We should either remove this section completely, or replace "Zen OSS Team" with "Mozilla".

### Expected behavior

The "protection tools" section in the menu either does not appear or say "Mozilla" instead of "Zen OSS Team"

### Actual behavior

The "protection tools" section in the menu says "Try other protection tools from Zen OSS Team"

### Steps to reproduce

1. Sign in to Zen with a Mozilla account.
2. edit the toolbar to make the account button appear
3. Click on the account button on the tool bar.
4. Observe the section titled "Try other protection tools from Zen OSS Team"
### Screenshots and videos

Image

### Version

1.16.4b

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Localization

### Relevant log output if applicable

```shell

```

### PR DESCRIPTION
**Pull request by MagentaManifold**
This is a fix for #10854. Here's a screenshot with this fix applied:

image

### CODE REVIEW

**Comment by MagentaManifold** [comment]
I couldn't figure out how to test this, but I think it's straight forward enough to not need a test (`_debloatContextMenus` doesn't have a test either, anyway). `_debloatContextMenus`'s method won't work for this issue, because these widgets are dynamically created on click.

File: src/zen/common/ZenUIManager.mjs [hunk 1]
```diff
@@ -125,6 +126,18 @@ var gZenUIManager = {
     }
   },
 
+  _debloatAppMenu() {
+    // Add CSS rules to hide Mozilla services from the app menu
+    const style = document.createElement('style');
```
Comment (mr-cheffy) [inline src/zen/common/ZenUIManager.mjs]: Why are you doing inline styles? We've talked yesterday that adding these IDs to the function below where we set the attributes `hideen=true` would work. Otherwise just do it in "single-components.css" maybe. But this is quite hacky imo

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

File: src/zen/common/ZenUIManager.mjs (hunk 1 above)
Comment (MagentaManifold) [reply src/zen/common/ZenUIManager.mjs]: I tried out what you said yesterday, but this sadly doesn't work the same way, because the menu is only created in the DOM when you click on the account button, after Zen UI manager is initialized. Moreover, these widgets are already conditionally displayed, i.e., their `hidden` property is already `true`, and Firefox's code changes it to `false` to display it, that why I chose to use `display: none`.

Comment (MagentaManifold) [reply src/zen/common/ZenUIManager.mjs]: Yeah, putting it in `zen-single-components.css` is better. I didn't do this yesterday because I didn't know which file is a good place to put it in 😅 (still very new to the codebase). I'll repush when I get time

Comment (MagentaManifold) [reply src/zen/common/ZenUIManager.mjs]: Done!

**Review by mr-cheffy — APPROVED** [review]
