### PR TITLE
Fixed macos signing process for browser entitlements

### LINKED ISSUE #437: Touch security key does not work
### What happened?

Touch ID security key does not work while attempting to login in gmail.

Screenshot 2024-08-22 at 13 35 06

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mr-cheffy**

### CODE REVIEW

File: src/browser/base/content/ZenStartup.mjs [hunk 1]
```diff
@@ -109,6 +109,9 @@
         });
       });
       observer.observe(tabsWrapper);
+      tabsWrapper.addEventListener('dblclick', (event) => {
```
Comment (vraravam) [inline src/browser/base/content/ZenStartup.mjs]: Not sure what this has to do with macos signing?

**Comment by gorkareplay** [comment]
Yay it's done

**Comment by owencmcgrath** [comment]
Just wanted to say thanks for your work on this, @mauro-balades! We appreciate the effort for this amazing feature. 

Passkey support makes Zen ten times better.

**Comment by mr-cheffy** [comment]
❤️

Everyone can finally unsubscribe from this issue 😊
