### PR TITLE
fix: Allow user override of zen.theme.border-radius pref value

### LINKED ISSUE #7004: "zen.theme.border-radius" dosen't work on linux.
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

"zen.theme.border-radius" in about:config used to work fine until version 1.7.2b.
but it does not change any border radius now. 
(issue is exclusive to linux)

Image

### Version

1.10.3b

### What platform are you seeing the problem on?

Linux (Flatpak)

### What component is this issue related to?

Customizable UI / Toolbars

### Relevant log output if applicable

```shell

```

### PR DESCRIPTION
**Pull request by busybox11**
Fixes #7004 

Tested and confirmed working on Windows and Linux. Don't have any macOS platform available to test this on yet.

Changed the `zen.theme.border-radius` property to use a default of `-1` (previously `8`) that `zen-theme.css` would treat as "auto-detect". Each platform defines its own override from the CSS rather than from build prefs.

Some notes:

- I'm not sure if `zenThemeModifier.updateBorderRadius` is still useful, even without these changes.

- As discussed in #7004, some other implementations would be possible and might be more desireable.

  Maybe setting the value in JS would have less overhead than CSS, especially if it's only computed once.
  On the other hand, CSS-only is convenient and perf impact is probably negligeable. Not 100% convinced of my approach here.

- The default value pref could be dropped altogether, to make every change intentional as the users will have to create the property by themselves. Not convinced, but worth mentioning (I hope)

### CODE REVIEW

File: src/zen/common/zenThemeModifier.js [hunk 1]
```diff
@@ -87,8 +87,14 @@ var ZenThemeModifier = {
   },
 
   updateBorderRadius() {
-    const borderRadius = Services.prefs.getIntPref('zen.theme.border-radius');
-    document.documentElement.style.setProperty('--zen-border-radius', borderRadius + 'px');
+    const borderRadius = Services.prefs.getIntPref('zen.theme.border-radius', -1);
+    // -1 is the default value, will use platform-native values
+    // otherwise, use the custom value
+    if (borderRadius == -1) {
+      document.documentElement.style.removeProperty('--zen-border-radius');
```
Comment (mr-cheffy) [inline src/zen/common/zenThemeModifier.js]: There are other elements that still use `zen-border-radius`, so I dont think we should be removing it.

Maybe we should do the nativity checks here? It would also clean up the CSS above and we would not need `--zen-native-content-radius` anymore, we could just use this one.

Checkout `AppConstants.platform` and `window.matchMedia('-moz-mac-tahoe-theme')`

**Review by mr-cheffy — CHANGES_REQUESTED** [review]

File: src/zen/common/zenThemeModifier.js (hunk 1 above)
Comment (busybox11) [reply src/zen/common/zenThemeModifier.js]: Right. Not a lot of them, just enough for me to forget about it since yesterday. My bad, sorry!

But yeah this is what I thought too. Went with CSS because it was fairly straight forward, but as I said in the notes, JS would have some advantages. 

Fixing this, thanks for the feedback!

Comment (busybox11) [reply src/zen/common/zenThemeModifier.js]: Hm, further into debugging it looks like `--zen-border-radius` is useless on `.folders-tabs-list-item`.

The hover radius shown to the user is actually coming from its only child, `.folders-tabs-list-item-content`.

Unsure why `&:first-child` and `&:last-child` are present in its style, as it always is the only children of its `.folders-tabs-list-item` parent. Maybe you'll know better, I can't find anything relevant.

The other remaining usage is in `.notificationbox-slack` but I'm not sure why it is not using the same radius var as the rest of the similar `zen-omnibox.css` declarations.

Regardless, I have implemented the JS-based `--zen-border-radius` and replaced all old occurencies of `--zen-native-content-radius`. Will push soon after test.

Comment (mr-cheffy) [reply src/zen/common/zenThemeModifier.js]: Regardless of whether its used, it would still be beneficial to remove the extra "native" arg and run all the checks on the JS side, so I wouldn't worry much about it tbh

Comment (busybox11) [reply src/zen/common/zenThemeModifier.js]: Yep, those won't see any change anyway. I'm not that familiar with the codebase so I took the time to investigate, but it's not a priority indeed.

lmk if I should also fix it in this PR, otherwise all good for me!

sidenote - this breaks some zen mod i forgot the name of that applies solid borders to the page frame. I guess it's expected though.

**Review by mr-cheffy — APPROVED** [review]

**Review by mr-cheffy — APPROVED** [review]
